### ISSUE TITLE
doc : statement of contributions

### ISSUE THREAD

**Issue by tjex** [tjex/ci-server-g26#2]

**Comment by Darpos** [comment]
Michael Morales Sundstedt:
Communication handling from webhook to JSONObject.
Git cloning the branch of which the webhook was pushed from.
Test for both of the above.
Added the build eval of cloned repo from branch (with @tjex)
Added description and context

**Comment by a-kbd** [comment]
Help with server configuration and testing
Help with debugging

**Comment by tjex** [comment]
closed with PR #49
